name: Generate XAML File
on:
  schedule:
    - cron: "0 16,18,20,22 * * 0-4"      # 北京工作日 00/02/04/06
    - cron: "*/30 22-23,0-15 * * 0-4"    # 北京工作日 06:00-23:30
    - cron: "*/30 16-23 * * 5"           # 北京 Sat 00-07:30
    - cron: "*/30 0-23 * * 6"            # 北京 Sat 08 - Sun 07:30
    - cron: "*/30 0-15 * * 0"            # 北京 Sun 08-23:30
  push:
    branches: [ main ]
    paths:
      - 'main.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'main.py'
  workflow_dispatch:

jobs:
  generate-xaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.COMMIT_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests
          pip install chinesecalendar
          pip install pytz

      - name: Run main.py
        env:
          Token: ${{ secrets.Token }}
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "EYiChengs-Robot"
          git config --global user.email "${{ secrets.EYICHENGSROBOTSGITCOMMITEMAIL }}"
          git add index.xaml index.xaml.ini
          git diff --cached --quiet || git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
